# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### IAM gateway routes configuration. ####
#
spring:
  cloud:
    # see:org.springframework.cloud.gateway.config.GatewayProperties
    gateway: # see:https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.0.0.RELEASE/single/spring-cloud-gateway.html#_requestratelimiter_gatewayfilter_factory
      routes:
        - id: v2-energy-openapi-service
          #uri: http://openapi.wl4gsafecloudcs.com
          uri: lb://v2-energy-openapi-service
          predicates:
            - Path=/v2/** # Only configured once???
            #- Weight=v2-energy-openapi-service,5
          filters:
            - name: SignTokenAuthing
              args:
                # Note: In some special business platform scenarios, the signature authentication protocol may not define
                # appId (such as Alibaba Cloud Market SaaS product authentication API), then the uniqueness of the client
                # application can only be determined according to the request route ID.
                app-id-extract-mode: Parameter
                # Only valid when appId extract mode is parameter.
                app-id-param: appId
                secret-param: key
                sign-param: signature
                sign-algorithm: S256
                sign-hashing-mode: SimpleParamsBytesSortedHashing
                sign-hashing-include-params: [appId, timestamp, nonce]
                sign-hashing-exclude-params: []
                sign-hashing-required-include-params: [appId, timestamp, nonce]
            #- StripPrefix=1
            # see: org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter#isAllowed()
            # see: https://blog.csdn.net/songhaifengshuaige/article/details/93372437
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率, 即等价于允许用户每秒处理多少个请求平均数
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的容量, 允许在一秒钟内完成的最大请求数
                redis-rate-limiter.burstCapacity: 1
                # 用于限流的键的解析器的 beanName。使用 SpEL 表达式获取 Bean
                key-resolver: '#{@hostKeyResolver}'
            # see: org.springframework.cloud.gateway.filter.factory.RewritePathGatewayFilterFactory#apply
            - RewritePath=/v2/(?<segment>.*), /openapi/v2/$\{segment}
        - id: v1-alimarket-openapi-service
          uri: lb://v1-alimarket-openapi-service
          predicates:
            - Path=/alimarket/v1/**
          filters:
            - name: SignTokenAuthing
              args:
                # Note: In some special business platform scenarios, the signature authentication protocol may not define
                # appId (such as Alibaba Cloud Market SaaS product authentication API), then the uniqueness of the client
                # application can only be determined according to the request route ID.
                app-id-extract-mode: RouteId
                # Only valid when appId extract mode is parameter.
                app-id-param: appId
                secret-param: key
                sign-param: token
                sign-algorithm: S256
                sign-hashing-mode: UriParamsKeySortedHashing
                sign-hashing-include-params: ['*']
                sign-hashing-exclude-params: []
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: '#{@hostKeyResolver}'
            # see: org.springframework.cloud.gateway.filter.factory.RewritePathGatewayFilterFactory#apply
            - RewritePath=/alimarket/v1/(?<segment>.*), /openapi/alimarket/v1/$\{segment}
        #- id: portal
        #  uri: https://www.qq.com
        #  predicates:
        #    - Path=/**
        #  filters:
        #    #- TokenRelay
        #    - TokenRelayRefresh
        #    - RemoveRequestHeader=Cookie, Set-Cookie
